# Generated by Django 4.1.6 on 2024-01-09 19:24

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("celery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="celerytask",
            name="kwargs",
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="celerytask",
            name="task_args",
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="celerytask",
            name="task_kwargs",
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
