# Generated by Django 4.1.6 on 2024-01-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("celery", "0002_celerytask_kwargs_alter_celerytask_task_args_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="celerytask",
            name="task_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
