# Generated by Django 4.1.7 on 2023-03-21 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_buildingproject_finished"),
        ("particular_task", "0002_added_assign_and_accepting_fields"),
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProjectDashboard",
            new_name="Dashboard",
        ),
    ]
