# Generated by Django 4.1.6 on 2023-10-23 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_projectgallery_and_more"),
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="project",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dashboard",
                to="projects.project",
            ),
        ),
    ]
