# Generated by Django 4.1.6 on 2023-11-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_alter_dashboard_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
