# Generated by Django 4.1.6 on 2023-11-22 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_project_main_image"),
        ("dashboard", "0004_alter_dashboard_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard",
                to="projects.project",
            ),
        ),
    ]
