# Generated by Django 4.1.6 on 2023-11-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_alter_dashboard_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
