# Generated by Django 4.1.6 on 2023-10-23 08:47

import uuid

from django.db import migrations, models

import apps.base_services


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=32)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "main_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=apps.base_services.generate_random_filename_for_project
                    ),
                ),
                ("finished", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectGallery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=apps.base_services.generate_random_filename_for_project
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="buildingproject",
            name="address",
        ),
        migrations.RemoveField(
            model_name="buildingproject",
            name="building_master",
        ),
        migrations.RemoveField(
            model_name="buildingproject",
            name="client",
        ),
        migrations.RemoveField(
            model_name="buildingproject",
            name="designer",
        ),
        migrations.RemoveField(
            model_name="buildingproject",
            name="owner",
        ),
    ]
