# Generated by Django 4.1.7 on 2023-03-16 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0002_changed_to_ForeignKey_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingproject",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Company realized this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner_project",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
