# Generated by Django 4.1.6 on 2023-10-23 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
        ("projects", "0002_project_projectgallery_and_more"),
        ("dashboard", "0002_alter_dashboard_project"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="BuildingProject",
        ),
        migrations.AddField(
            model_name="projectgallery",
            name="project",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.project"),
        ),
        migrations.AddField(
            model_name="project",
            name="address",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="authentication.address"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="building_master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="master_project",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_project",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="designer",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Person who create this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="designer_project",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
