# Generated by Django 4.1.7 on 2023-03-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_buildingproject_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingproject",
            name="finished",
            field=models.BooleanField(default=False),
        ),
    ]
