# Generated by Django 4.1.6 on 2023-10-25 17:07

import django.db.models.deletion
from django.db import migrations, models

import apps.base_services


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_delete_buildingproject_projectgallery_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="main_image",
            field=models.ImageField(upload_to=apps.base_services.generate_random_filename_for_project),
        ),
        migrations.AlterField(
            model_name="projectgallery",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="project_gallery", to="projects.project"
            ),
        ),
    ]
