# Generated by Django 4.1.6 on 2023-10-28 23:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_project_client_alter_project_main_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectGallery",
        ),
    ]
