# Generated by Django 4.1.6 on 2023-10-28 23:52

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.base_services


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0005_delete_projectgallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageAsset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=apps.base_services.generate_random_filename_for_project
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="image_gallery", to="projects.project"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
