# Generated by Django 4.1.6 on 2023-11-24 14:39

from django.db import migrations, models


def generate_size(apps, schema_editor):
    ImageAsset = apps.get_model("images", "ImageAsset")
    for image in ImageAsset.objects.all():
        image.save()


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_imageasset_image_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageasset",
            name="image_size",
            field=models.TextField(editable=False, null=True, blank=True),
        ),
        migrations.RunPython(generate_size),
        migrations.AlterField(
            model_name="imageasset",
            name="image_size",
            field=models.TextField(default=0, editable=False),
        ),
    ]
