# Generated by Django 4.1.6 on 2023-11-27 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0003_imageasset_image_size"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imageasset",
            options={"verbose_name": "Image"},
        ),
    ]
