# Generated by Django 4.1.6 on 2023-12-31 15:42

from django.db import migrations, models

import apps.base_services


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0005_imageasset_task_alter_imageasset_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageasset",
            name="image",
            field=models.ImageField(
                blank=True, max_length=256, null=True, upload_to=apps.base_services.generate_random_filename_for_project
            ),
        ),
    ]
