version: '3.9'

services:
  db:
    image: "postgis/postgis:12-3.2"
    env_file:
      - secrets/.env.postgres
    ports:
      - "5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - secrets/.env.dev
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web
    user: root
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db

# FIXME: add new container ngrok to connect localhost
#  ngrok:
#    image: wernight/ngrok
#    restart: unless-stopped
#    ports:
#      - "4040:4040"
#    volumes:
#      - ./.ngrok.yml:/ngrok/.ngrok.yml
#      - ./secrets/.env.ngrok:/ngrok/.env.ngrok
#    command:
#      - "/bin/sh"
#      - "-c"
#      - "ngrok start --config /ngrok/.ngrok.yml --all"
