# Generated by Django 4.1.6 on 2023-11-29 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_alter_dashboard_name"),
        ("particular_task", "0003_alter_task_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="photo",
        ),
        migrations.AlterField(
            model_name="task",
            name="dashboard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task",
                to="dashboard.dashboard",
            ),
        ),
    ]
