# Generated by Django 4.1.6 on 2023-12-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("particular_task", "0004_remove_task_photo_alter_task_dashboard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
