# Generated by Django 4.1.6 on 2024-01-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("particular_task", "0005_alter_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
