# Generated by Django 4.1.7 on 2023-03-16 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comments", "0001_initial"),
        ("particular_task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentary",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentary",
                to="particular_task.particulartask",
            ),
        ),
    ]
