# Generated by Django 4.1.6 on 2023-12-16 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("particular_task", "0004_remove_task_photo_alter_task_dashboard"),
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentary",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentary",
                to="particular_task.task",
            ),
        ),
    ]
