# Generated by Django 4.1.6 on 2023-10-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_line_1",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="address",
            name="post_code",
            field=models.CharField(max_length=32),
        ),
    ]
