# Generated by Django 4.1.7 on 2023-03-20 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="authentication.address"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(choices=[("PL", "PL"), ("EN", "EN"), ("UA", "UA")], default="EN", max_length=2),
        ),
    ]
