# Generated by Django 4.1.6 on 2023-11-08 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_address_created_at_address_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="authentication.address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
