# Generated by Django 4.1.6 on 2023-12-16 11:29

from django.db import migrations, models

import apps.base_services


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_alter_address_updated_at_alter_user_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.base_services.generate_random_filename_for_user_avatar
            ),
        ),
    ]
